/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnswerChoice = IDL.Variant({
  'A' : IDL.Null,
  'B' : IDL.Null,
  'C' : IDL.Null,
  'D' : IDL.Null,
  'E' : IDL.Null,
  'None' : IDL.Null,
});
export const QuestionKey = IDL.Record({
  'pointValue' : IDL.Float64,
  'correctAnswer' : AnswerChoice,
  'questionNumber' : IDL.Nat,
});
export const AnswerKeyInput = IDL.Record({
  'name' : IDL.Text,
  'penaltyPerWrong' : IDL.Float64,
  'questions' : IDL.Vec(QuestionKey),
  'questionCount' : IDL.Nat,
});
export const AnswerKeyId = IDL.Nat;
export const AnswerKey = IDL.Record({
  'id' : AnswerKeyId,
  'name' : IDL.Text,
  'penaltyPerWrong' : IDL.Float64,
  'questions' : IDL.Vec(QuestionKey),
  'questionCount' : IDL.Nat,
});
export const ScanResultId = IDL.Nat;
export const AnswerStatus = IDL.Variant({
  'correct' : IDL.Null,
  'empty' : IDL.Null,
  'incorrect' : IDL.Null,
  'anomaly' : IDL.Null,
});
export const QuestionResult = IDL.Record({
  'status' : AnswerStatus,
  'pointsAwarded' : IDL.Float64,
  'detectedAnswer' : IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'D' : IDL.Null,
    'E' : IDL.Null,
    'None' : IDL.Null,
  }),
  'questionNumber' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const ScanResult = IDL.Record({
  'id' : ScanResultId,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'answerKeyId' : AnswerKeyId,
  'questionResults' : IDL.Vec(QuestionResult),
  'totalScore' : IDL.Float64,
  'timestamp' : Timestamp,
  'studentClass' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const ScoreBreakdown = IDL.Record({
  'questionResults' : IDL.Vec(QuestionResult),
  'maxPossibleScore' : IDL.Float64,
  'totalScore' : IDL.Float64,
  'incorrectCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'emptyCount' : IDL.Nat,
  'percentage' : IDL.Float64,
  'anomalyCount' : IDL.Nat,
});
export const ScanInput = IDL.Record({
  'studentId' : IDL.Text,
  'detectedAnswers' : IDL.Vec(
    IDL.Variant({
      'A' : IDL.Null,
      'B' : IDL.Null,
      'C' : IDL.Null,
      'D' : IDL.Null,
      'E' : IDL.Null,
      'None' : IDL.Null,
    })
  ),
  'studentName' : IDL.Text,
  'answerKeyId' : AnswerKeyId,
  'studentClass' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAnswerKey' : IDL.Func([AnswerKeyInput], [AnswerKey], []),
  'deleteAnswerKey' : IDL.Func([AnswerKeyId], [IDL.Bool], []),
  'deleteScanResult' : IDL.Func([ScanResultId], [IDL.Bool], []),
  'getAnswerKey' : IDL.Func([AnswerKeyId], [IDL.Opt(AnswerKey)], ['query']),
  'getScanResult' : IDL.Func([ScanResultId], [IDL.Opt(ScanResult)], ['query']),
  'gradeAnswers' : IDL.Func(
      [
        AnswerKeyId,
        IDL.Vec(
          IDL.Variant({
            'A' : IDL.Null,
            'B' : IDL.Null,
            'C' : IDL.Null,
            'D' : IDL.Null,
            'E' : IDL.Null,
            'None' : IDL.Null,
          })
        ),
      ],
      [IDL.Opt(ScoreBreakdown)],
      ['query'],
    ),
  'listAnswerKeys' : IDL.Func([], [IDL.Vec(AnswerKey)], ['query']),
  'listScanResults' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
  'submitScan' : IDL.Func([ScanInput], [ScanResult], []),
  'updateAnswerKey' : IDL.Func([AnswerKeyId, AnswerKeyInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnswerChoice = IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'D' : IDL.Null,
    'E' : IDL.Null,
    'None' : IDL.Null,
  });
  const QuestionKey = IDL.Record({
    'pointValue' : IDL.Float64,
    'correctAnswer' : AnswerChoice,
    'questionNumber' : IDL.Nat,
  });
  const AnswerKeyInput = IDL.Record({
    'name' : IDL.Text,
    'penaltyPerWrong' : IDL.Float64,
    'questions' : IDL.Vec(QuestionKey),
    'questionCount' : IDL.Nat,
  });
  const AnswerKeyId = IDL.Nat;
  const AnswerKey = IDL.Record({
    'id' : AnswerKeyId,
    'name' : IDL.Text,
    'penaltyPerWrong' : IDL.Float64,
    'questions' : IDL.Vec(QuestionKey),
    'questionCount' : IDL.Nat,
  });
  const ScanResultId = IDL.Nat;
  const AnswerStatus = IDL.Variant({
    'correct' : IDL.Null,
    'empty' : IDL.Null,
    'incorrect' : IDL.Null,
    'anomaly' : IDL.Null,
  });
  const QuestionResult = IDL.Record({
    'status' : AnswerStatus,
    'pointsAwarded' : IDL.Float64,
    'detectedAnswer' : IDL.Variant({
      'A' : IDL.Null,
      'B' : IDL.Null,
      'C' : IDL.Null,
      'D' : IDL.Null,
      'E' : IDL.Null,
      'None' : IDL.Null,
    }),
    'questionNumber' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const ScanResult = IDL.Record({
    'id' : ScanResultId,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'answerKeyId' : AnswerKeyId,
    'questionResults' : IDL.Vec(QuestionResult),
    'totalScore' : IDL.Float64,
    'timestamp' : Timestamp,
    'studentClass' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const ScoreBreakdown = IDL.Record({
    'questionResults' : IDL.Vec(QuestionResult),
    'maxPossibleScore' : IDL.Float64,
    'totalScore' : IDL.Float64,
    'incorrectCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'emptyCount' : IDL.Nat,
    'percentage' : IDL.Float64,
    'anomalyCount' : IDL.Nat,
  });
  const ScanInput = IDL.Record({
    'studentId' : IDL.Text,
    'detectedAnswers' : IDL.Vec(
      IDL.Variant({
        'A' : IDL.Null,
        'B' : IDL.Null,
        'C' : IDL.Null,
        'D' : IDL.Null,
        'E' : IDL.Null,
        'None' : IDL.Null,
      })
    ),
    'studentName' : IDL.Text,
    'answerKeyId' : AnswerKeyId,
    'studentClass' : IDL.Text,
  });
  
  return IDL.Service({
    'createAnswerKey' : IDL.Func([AnswerKeyInput], [AnswerKey], []),
    'deleteAnswerKey' : IDL.Func([AnswerKeyId], [IDL.Bool], []),
    'deleteScanResult' : IDL.Func([ScanResultId], [IDL.Bool], []),
    'getAnswerKey' : IDL.Func([AnswerKeyId], [IDL.Opt(AnswerKey)], ['query']),
    'getScanResult' : IDL.Func(
        [ScanResultId],
        [IDL.Opt(ScanResult)],
        ['query'],
      ),
    'gradeAnswers' : IDL.Func(
        [
          AnswerKeyId,
          IDL.Vec(
            IDL.Variant({
              'A' : IDL.Null,
              'B' : IDL.Null,
              'C' : IDL.Null,
              'D' : IDL.Null,
              'E' : IDL.Null,
              'None' : IDL.Null,
            })
          ),
        ],
        [IDL.Opt(ScoreBreakdown)],
        ['query'],
      ),
    'listAnswerKeys' : IDL.Func([], [IDL.Vec(AnswerKey)], ['query']),
    'listScanResults' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
    'submitScan' : IDL.Func([ScanInput], [ScanResult], []),
    'updateAnswerKey' : IDL.Func([AnswerKeyId, AnswerKeyInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };