/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnswerChoice = { 'A' : null } |
  { 'B' : null } |
  { 'C' : null } |
  { 'D' : null } |
  { 'E' : null } |
  { 'None' : null };
export interface AnswerKey {
  'id' : AnswerKeyId,
  'name' : string,
  'penaltyPerWrong' : number,
  'questions' : Array<QuestionKey>,
  'questionCount' : bigint,
}
export type AnswerKeyId = bigint;
export interface AnswerKeyInput {
  'name' : string,
  'penaltyPerWrong' : number,
  'questions' : Array<QuestionKey>,
  'questionCount' : bigint,
}
export type AnswerStatus = { 'correct' : null } |
  { 'empty' : null } |
  { 'incorrect' : null } |
  { 'anomaly' : null };
export interface QuestionKey {
  'pointValue' : number,
  'correctAnswer' : AnswerChoice,
  'questionNumber' : bigint,
}
export interface QuestionResult {
  'status' : AnswerStatus,
  'pointsAwarded' : number,
  'detectedAnswer' : { 'A' : null } |
    { 'B' : null } |
    { 'C' : null } |
    { 'D' : null } |
    { 'E' : null } |
    { 'None' : null },
  'questionNumber' : bigint,
}
export interface ScanInput {
  'studentId' : string,
  'detectedAnswers' : Array<
    { 'A' : null } |
      { 'B' : null } |
      { 'C' : null } |
      { 'D' : null } |
      { 'E' : null } |
      { 'None' : null }
  >,
  'studentName' : string,
  'answerKeyId' : AnswerKeyId,
  'studentClass' : string,
}
export interface ScanResult {
  'id' : ScanResultId,
  'studentId' : string,
  'studentName' : string,
  'answerKeyId' : AnswerKeyId,
  'questionResults' : Array<QuestionResult>,
  'totalScore' : number,
  'timestamp' : Timestamp,
  'studentClass' : string,
  'percentage' : number,
}
export type ScanResultId = bigint;
export interface ScoreBreakdown {
  'questionResults' : Array<QuestionResult>,
  'maxPossibleScore' : number,
  'totalScore' : number,
  'incorrectCount' : bigint,
  'correctCount' : bigint,
  'emptyCount' : bigint,
  'percentage' : number,
  'anomalyCount' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'createAnswerKey' : ActorMethod<[AnswerKeyInput], AnswerKey>,
  'deleteAnswerKey' : ActorMethod<[AnswerKeyId], boolean>,
  'deleteScanResult' : ActorMethod<[ScanResultId], boolean>,
  'getAnswerKey' : ActorMethod<[AnswerKeyId], [] | [AnswerKey]>,
  'getScanResult' : ActorMethod<[ScanResultId], [] | [ScanResult]>,
  'gradeAnswers' : ActorMethod<
    [
      AnswerKeyId,
      Array<
        { 'A' : null } |
          { 'B' : null } |
          { 'C' : null } |
          { 'D' : null } |
          { 'E' : null } |
          { 'None' : null }
      >,
    ],
    [] | [ScoreBreakdown]
  >,
  'listAnswerKeys' : ActorMethod<[], Array<AnswerKey>>,
  'listScanResults' : ActorMethod<[], Array<ScanResult>>,
  'submitScan' : ActorMethod<[ScanInput], ScanResult>,
  'updateAnswerKey' : ActorMethod<[AnswerKeyId, AnswerKeyInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];