/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScoreBreakdown {
    questionResults: Array<QuestionResult>;
    maxPossibleScore: number;
    totalScore: number;
    incorrectCount: bigint;
    correctCount: bigint;
    emptyCount: bigint;
    percentage: number;
    anomalyCount: bigint;
}
export type Timestamp = bigint;
export interface AnswerKeyInput {
    name: string;
    penaltyPerWrong: number;
    questions: Array<QuestionKey>;
    questionCount: bigint;
}
export interface ScanResult {
    id: ScanResultId;
    studentId: string;
    studentName: string;
    answerKeyId: AnswerKeyId;
    questionResults: Array<QuestionResult>;
    totalScore: number;
    timestamp: Timestamp;
    studentClass: string;
    percentage: number;
}
export interface ScanInput {
    studentId: string;
    detectedAnswers: Array<Variant_A_B_C_D_E_None>;
    studentName: string;
    answerKeyId: AnswerKeyId;
    studentClass: string;
}
export interface AnswerKey {
    id: AnswerKeyId;
    name: string;
    penaltyPerWrong: number;
    questions: Array<QuestionKey>;
    questionCount: bigint;
}
export interface QuestionKey {
    pointValue: number;
    correctAnswer: AnswerChoice;
    questionNumber: bigint;
}
export type ScanResultId = bigint;
export type AnswerKeyId = bigint;
export interface QuestionResult {
    status: AnswerStatus;
    pointsAwarded: number;
    detectedAnswer: Variant_A_B_C_D_E_None;
    questionNumber: bigint;
}
export enum AnswerStatus {
    correct = "correct",
    empty = "empty",
    incorrect = "incorrect",
    anomaly = "anomaly"
}
export enum Variant_A_B_C_D_E_None {
    A = "A",
    B = "B",
    C = "C",
    D = "D",
    E = "E",
    None = "None"
}
export interface backendInterface {
    createAnswerKey(input: AnswerKeyInput): Promise<AnswerKey>;
    deleteAnswerKey(id: AnswerKeyId): Promise<boolean>;
    deleteScanResult(id: ScanResultId): Promise<boolean>;
    getAnswerKey(id: AnswerKeyId): Promise<AnswerKey | null>;
    getScanResult(id: ScanResultId): Promise<ScanResult | null>;
    gradeAnswers(answerKeyId: AnswerKeyId, detectedAnswers: Array<Variant_A_B_C_D_E_None>): Promise<ScoreBreakdown | null>;
    listAnswerKeys(): Promise<Array<AnswerKey>>;
    listScanResults(): Promise<Array<ScanResult>>;
    submitScan(input: ScanInput): Promise<ScanResult>;
    updateAnswerKey(id: AnswerKeyId, input: AnswerKeyInput): Promise<boolean>;
}
import type { AnswerChoice as _AnswerChoice, AnswerKey as _AnswerKey, AnswerKeyId as _AnswerKeyId, AnswerKeyInput as _AnswerKeyInput, AnswerStatus as _AnswerStatus, QuestionKey as _QuestionKey, QuestionResult as _QuestionResult, ScanInput as _ScanInput, ScanResult as _ScanResult, ScanResultId as _ScanResultId, ScoreBreakdown as _ScoreBreakdown, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAnswerKey(arg0: AnswerKeyInput): Promise<AnswerKey> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnswerKey(to_candid_AnswerKeyInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnswerKey_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnswerKey(to_candid_AnswerKeyInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnswerKey_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnswerKey(arg0: AnswerKeyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnswerKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnswerKey(arg0);
            return result;
        }
    }
    async deleteScanResult(arg0: ScanResultId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScanResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScanResult(arg0);
            return result;
        }
    }
    async getAnswerKey(arg0: AnswerKeyId): Promise<AnswerKey | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnswerKey(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnswerKey(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScanResult(arg0: ScanResultId): Promise<ScanResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScanResult(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScanResult(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeAnswers(arg0: AnswerKeyId, arg1: Array<Variant_A_B_C_D_E_None>): Promise<ScoreBreakdown | null> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeAnswers(arg0, to_candid_vec_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeAnswers(arg0, to_candid_vec_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnswerKeys(): Promise<Array<AnswerKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnswerKeys();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnswerKeys();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listScanResults(): Promise<Array<ScanResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScanResults();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScanResults();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitScan(arg0: ScanInput): Promise<ScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScan(to_candid_ScanInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ScanResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScan(to_candid_ScanInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ScanResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnswerKey(arg0: AnswerKeyId, arg1: AnswerKeyInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnswerKey(arg0, to_candid_AnswerKeyInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnswerKey(arg0, to_candid_AnswerKeyInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AnswerChoice_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerChoice): AnswerChoice {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AnswerKey_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerKey): AnswerKey {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AnswerStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerStatus): AnswerStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionKey_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionKey): QuestionKey {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionResult): QuestionResult {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ScanResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanResult): ScanResult {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ScoreBreakdown_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoreBreakdown): ScoreBreakdown {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnswerKey]): AnswerKey | null {
    return value.length === 0 ? null : from_candid_AnswerKey_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanResult]): ScanResult | null {
    return value.length === 0 ? null : from_candid_ScanResult_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScoreBreakdown]): ScoreBreakdown | null {
    return value.length === 0 ? null : from_candid_ScoreBreakdown_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pointValue: number;
    correctAnswer: _AnswerChoice;
    questionNumber: bigint;
}): {
    pointValue: number;
    correctAnswer: AnswerChoice;
    questionNumber: bigint;
} {
    return {
        pointValue: value.pointValue,
        correctAnswer: from_candid_AnswerChoice_n13(_uploadFile, _downloadFile, value.correctAnswer),
        questionNumber: value.questionNumber
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScanResultId;
    studentId: string;
    studentName: string;
    answerKeyId: _AnswerKeyId;
    questionResults: Array<_QuestionResult>;
    totalScore: number;
    timestamp: _Timestamp;
    studentClass: string;
    percentage: number;
}): {
    id: ScanResultId;
    studentId: string;
    studentName: string;
    answerKeyId: AnswerKeyId;
    questionResults: Array<QuestionResult>;
    totalScore: number;
    timestamp: Timestamp;
    studentClass: string;
    percentage: number;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        studentName: value.studentName,
        answerKeyId: value.answerKeyId,
        questionResults: from_candid_vec_n19(_uploadFile, _downloadFile, value.questionResults),
        totalScore: value.totalScore,
        timestamp: value.timestamp,
        studentClass: value.studentClass,
        percentage: value.percentage
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AnswerStatus;
    pointsAwarded: number;
    detectedAnswer: {
        A: null;
    } | {
        B: null;
    } | {
        C: null;
    } | {
        D: null;
    } | {
        E: null;
    } | {
        None: null;
    };
    questionNumber: bigint;
}): {
    status: AnswerStatus;
    pointsAwarded: number;
    detectedAnswer: Variant_A_B_C_D_E_None;
    questionNumber: bigint;
} {
    return {
        status: from_candid_AnswerStatus_n22(_uploadFile, _downloadFile, value.status),
        pointsAwarded: value.pointsAwarded,
        detectedAnswer: from_candid_variant_n14(_uploadFile, _downloadFile, value.detectedAnswer),
        questionNumber: value.questionNumber
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questionResults: Array<_QuestionResult>;
    maxPossibleScore: number;
    totalScore: number;
    incorrectCount: bigint;
    correctCount: bigint;
    emptyCount: bigint;
    percentage: number;
    anomalyCount: bigint;
}): {
    questionResults: Array<QuestionResult>;
    maxPossibleScore: number;
    totalScore: number;
    incorrectCount: bigint;
    correctCount: bigint;
    emptyCount: bigint;
    percentage: number;
    anomalyCount: bigint;
} {
    return {
        questionResults: from_candid_vec_n19(_uploadFile, _downloadFile, value.questionResults),
        maxPossibleScore: value.maxPossibleScore,
        totalScore: value.totalScore,
        incorrectCount: value.incorrectCount,
        correctCount: value.correctCount,
        emptyCount: value.emptyCount,
        percentage: value.percentage,
        anomalyCount: value.anomalyCount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnswerKeyId;
    name: string;
    penaltyPerWrong: number;
    questions: Array<_QuestionKey>;
    questionCount: bigint;
}): {
    id: AnswerKeyId;
    name: string;
    penaltyPerWrong: number;
    questions: Array<QuestionKey>;
    questionCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        penaltyPerWrong: value.penaltyPerWrong,
        questions: from_candid_vec_n10(_uploadFile, _downloadFile, value.questions),
        questionCount: value.questionCount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    D: null;
} | {
    E: null;
} | {
    None: null;
}): Variant_A_B_C_D_E_None {
    return "A" in value ? Variant_A_B_C_D_E_None.A : "B" in value ? Variant_A_B_C_D_E_None.B : "C" in value ? Variant_A_B_C_D_E_None.C : "D" in value ? Variant_A_B_C_D_E_None.D : "E" in value ? Variant_A_B_C_D_E_None.E : "None" in value ? Variant_A_B_C_D_E_None.None : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    correct: null;
} | {
    empty: null;
} | {
    incorrect: null;
} | {
    anomaly: null;
}): AnswerStatus {
    return "correct" in value ? AnswerStatus.correct : "empty" in value ? AnswerStatus.empty : "incorrect" in value ? AnswerStatus.incorrect : "anomaly" in value ? AnswerStatus.anomaly : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionKey>): Array<QuestionKey> {
    return value.map((x)=>from_candid_QuestionKey_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionResult>): Array<QuestionResult> {
    return value.map((x)=>from_candid_QuestionResult_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnswerKey>): Array<AnswerKey> {
    return value.map((x)=>from_candid_AnswerKey_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanResult>): Array<ScanResult> {
    return value.map((x)=>from_candid_ScanResult_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AnswerChoice_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerChoice): _AnswerChoice {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_AnswerKeyInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerKeyInput): _AnswerKeyInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionKey_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionKey): _QuestionKey {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ScanInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanInput): _ScanInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    penaltyPerWrong: number;
    questions: Array<QuestionKey>;
    questionCount: bigint;
}): {
    name: string;
    penaltyPerWrong: number;
    questions: Array<_QuestionKey>;
    questionCount: bigint;
} {
    return {
        name: value.name,
        penaltyPerWrong: value.penaltyPerWrong,
        questions: to_candid_vec_n3(_uploadFile, _downloadFile, value.questions),
        questionCount: value.questionCount
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    detectedAnswers: Array<Variant_A_B_C_D_E_None>;
    studentName: string;
    answerKeyId: AnswerKeyId;
    studentClass: string;
}): {
    studentId: string;
    detectedAnswers: Array<{
        A: null;
    } | {
        B: null;
    } | {
        C: null;
    } | {
        D: null;
    } | {
        E: null;
    } | {
        None: null;
    }>;
    studentName: string;
    answerKeyId: _AnswerKeyId;
    studentClass: string;
} {
    return {
        studentId: value.studentId,
        detectedAnswers: to_candid_vec_n24(_uploadFile, _downloadFile, value.detectedAnswers),
        studentName: value.studentName,
        answerKeyId: value.answerKeyId,
        studentClass: value.studentClass
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pointValue: number;
    correctAnswer: AnswerChoice;
    questionNumber: bigint;
}): {
    pointValue: number;
    correctAnswer: _AnswerChoice;
    questionNumber: bigint;
} {
    return {
        pointValue: value.pointValue,
        correctAnswer: to_candid_AnswerChoice_n6(_uploadFile, _downloadFile, value.correctAnswer),
        questionNumber: value.questionNumber
    };
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_A_B_C_D_E_None): {
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    D: null;
} | {
    E: null;
} | {
    None: null;
} {
    return value == Variant_A_B_C_D_E_None.A ? {
        A: null
    } : value == Variant_A_B_C_D_E_None.B ? {
        B: null
    } : value == Variant_A_B_C_D_E_None.C ? {
        C: null
    } : value == Variant_A_B_C_D_E_None.D ? {
        D: null
    } : value == Variant_A_B_C_D_E_None.E ? {
        E: null
    } : value == Variant_A_B_C_D_E_None.None ? {
        None: null
    } : value;
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Variant_A_B_C_D_E_None>): Array<{
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    D: null;
} | {
    E: null;
} | {
    None: null;
}> {
    return value.map((x)=>to_candid_variant_n7(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<QuestionKey>): Array<_QuestionKey> {
    return value.map((x)=>to_candid_QuestionKey_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
